Fix: #89 - 북마크 폴더 내부 이벤트 조회 오류 수정
duck-map-project/duck-map-be pull request #101
Opened 2023-05-26 17:48 UTC by busymidnight

## Description

> 북마크 폴더 내부 이벤트 조회 오류 수정 및 기능 개선

## Changes
- BookmarkFolderRepositoryImpl 쿼리dsl 수정
- BookmarkFolderRepositoryTest 내용 추가
- BookmarkFolderRepositoryTest @Test import 변경

## ETC

2023-05-27 08:13 UTC, LeeRim requested changes

2023-05-27 08:13 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
> +				.leftJoin(eventBookmark.eventBookmarkFolder, eventBookmarkFolder)
eventBookmark가 이미 eventbookmarkFolder.id를 갖고 있어서 join 안해도 될거 같아요

2023-05-28 04:17 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
> +				.leftJoin(eventBookmark.eventBookmarkFolder, eventBookmarkFolder)
> eventBookmark가 이미 eventbookmarkFolder.id를 갖고 있어서 join 안해도 될거 같아요

Where에서 bookmarkFolderId 검색해야해요!

2023-05-28 04:47 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
> +				.leftJoin(eventBookmark.eventBookmarkFolder, eventBookmarkFolder)
엇 테스트가 잘 돌아가서 놓쳤네용 수정할게요!

2023-05-28 04:49 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
> +				.leftJoin(eventBookmark.eventBookmarkFolder, eventBookmarkFolder)
> 엇 테스트가 잘 돌아가서 놓쳤네용 수정할게요! 

그러면 테스트 코드도 잘못된거 같아요

2023-05-28 04:59 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
> +				.leftJoin(eventBookmark.eventBookmarkFolder, eventBookmarkFolder)
네네 방금 테스트 코드 돌려보고 안 돌아가는 것 확인했습니다

2023-05-28 10:12 UTC, LeeRim requested changes

2023-05-28 10:12 UTC, LeeRim commented on src/test/java/com/teamddd/duckmap/BookmarkFolderRepositoryTest.java
> +		eventBookmark.getEventBookmarkFolder().getEventBookmarks().add(eventBookmark);
이거 add 안해주셔도 돼요! JPA 활용2 강의에 컬렉션 조회 최적화 부분에 나와요

2023-05-28 10:12 UTC, LeeRim commented on src/test/java/com/teamddd/duckmap/BookmarkFolderRepositoryTest.java
> +		EventBookmarkFolder eventBookmarkFolder = createEventBookmarkFolder();
여러 event중에 folder id로 검색하는 로직이라 folder가 여러개 있어야 test 의미가 더 살거 같아요

2023-05-28 12:35 UTC, LeeRim approved these changes

2023-05-28 12:36 UTC, merged