좋아요 기능 Mock api 생성
duck-map-project/duck-map-be pull request #13
Opened 2023-05-16 15:21 UTC by busymidnight

## Description
> 좋아요, 좋아요 취소 mock api 생성

## Chages
- LikeController 
- POST /events/{id}/likes
- DELETE /events/{id}/likes

## ETC

2023-05-16 16:15 UTC, LeeRim requested changes

2023-05-16 16:15 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/LikeController.java
> +	public Result<LikeRes> likeEvent(@PathVariable Long id, @Validated @RequestBody LikeReq likeReq) {
event id는 pathVariable에서 받고, user id는 로그인 session에서 받으면 될거 같아요
그래서 LikeReq가 없어도 되지 않을까요?

2023-05-16 16:48 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/controller/LikeController.java
> +	public Result<LikeRes> likeEvent(@PathVariable Long id, @Validated @RequestBody LikeReq likeReq) {
넵 그러면 LikeReq는 삭제하도록 할게요
그러면 likeEvent에서 HttpSession으로 session을 받으면 될까요?

2023-05-16 16:51 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/LikeController.java
> +	public Result<LikeRes> likeEvent(@PathVariable Long id, @Validated @RequestBody LikeReq likeReq) {
네 service단에서 처리하면 될거 같아요

2023-05-17 04:29 UTC, LeeRim approved these changes

2023-05-17 04:30 UTC, LeeRim requested changes
main이 아니라 mock-api branch에 merge 해야해요!

2023-05-17 04:30 UTC, closed without merging