아티스트 구분 CRUD api 생성
duck-map-project/duck-map-be pull request #22
Opened 2023-05-18 11:05 UTC by busymidnight

## Description
> ArtistType CRUD Mock api 생성

## Chages
- ArtistTypeController 
  - POST /artists/types
  - GET /artists/types
  - PUT /artist/types/{id}
  - DELETE /artists/types/{id}
- CreateArtistTypeRes, CreateArtistTypeReq, UpdateArtistTypeReq, ArtistTypeRes 생성

## ETC
- swagger로 mock api Test 필수 진행 후 커밋

2023-05-18 11:14 UTC, LeeRim requested changes

2023-05-18 11:14 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/CreateArtistTypeReq.java
> +	private Long id;
생성 시에는 pk 안받아서 삭제해주세요

2023-05-18 11:17 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/dto/CreateArtistTypeReq.java
> +	private Long id;
앗 그럼 Id 자동 생성하는 엔티티들도 다 동일한가요?

2023-05-18 11:19 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/dto/CreateArtistTypeReq.java
> +	private Long id;
> 생성 시에는 pk 안받아서 삭제해주세요

앗 그럼 Id 자동 생성하는 엔티티들도 다 동일한가요?

2023-05-18 11:23 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/CreateArtistTypeReq.java
> +	private Long id;
넵 create하는 api는 id 값 안받아요

2023-05-18 11:33 UTC, LeeRim requested changes

2023-05-18 11:33 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/UpdateArtistTypeReq.java
> +	private Long id;
자꾸 놓쳐서 죄송해요ㅠㅠ update pk도 pathVariable로 받아서 id 입력 삭제해도 될거 같아요

2023-05-18 11:35 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/dto/UpdateArtistTypeReq.java
> +	private Long id;
> 자꾸 놓쳐서 죄송해요ㅠㅠ update pk도 pathVariable로 받아서 id 입력 삭제해도 될거 같아요

아! 그러네요 감사합니다!!

2023-05-19 03:39 UTC, LeeRim requested changes
이번에는 확실히 신경쓰신게 느껴져요!! 👍

2023-05-19 03:39 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/ArtistController.java
> +					.groupId(1L)
세븐틴이 그룹이라 groupId null이어야 할거 같아요

2023-05-19 03:39 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/ArtistController.java
> +	public Result<Void> updateArtist(@PathVariable Long id, @RequestBody UpdateArtistReq updateArtistReq) {
@Validated 추가해주세요

2023-05-19 03:39 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
> +	public Result<Void> updateArtistType(@PathVariable Long id, @RequestBody UpdateArtistTypeReq updateArtistTypeReq) {
@Validated 추가해주세요

2023-05-19 03:39 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/ArtistController.java
> +	public Page<ArtistRes> getAllArtists(Pageable pageable) {
나중에 아티스트 타입이랑 아티스트 이름으로 조회할 수 있게 검색조건 넣어주세요

2023-05-19 06:35 UTC, LeeRim requested changes

2023-05-19 06:35 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
> +	public Page<ArtistTypeRes> getAllArtistType(Pageable pageable, ArtistSearchCondition searchCondition) {
아티시트 구분 조회할 때 ArtistSearchCondition이 필요한가요..?

2023-05-19 06:35 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/ArtistSearchCondition.java
> +@Data
@Data는 안쓰는게 좋아요
ModelAttribute dto라서 @Getter랑 @Builder있으면 될거 같아요

2023-05-19 06:35 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/ArtistSearchCondition.java
> +public class ArtistSearchCondition {
제안사항인데 쿼리 파라미터 dto니까 Condition대신 Param이라고 명명하는거 어떠세요??

2023-05-19 06:35 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/ArtistSearchCondition.java
> +	private String artistType;
artistTypeId 값을 받는게 로직짤 때 편할거 같아요

2023-05-19 06:51 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
> +	public Page<ArtistTypeRes> getAllArtistType(Pageable pageable, ArtistSearchCondition searchCondition) {
아 아티스트 조회할때만 쓰는군요?! 알겠습니다

2023-05-19 06:52 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/dto/ArtistSearchCondition.java
> +public class ArtistSearchCondition {
넵 좋아요!

2023-05-19 07:05 UTC, LeeRim approved these changes

2023-05-19 07:06 UTC, merged