Event CRUD api 수정
duck-map-project/duck-map-be pull request #23
Opened 2023-05-18 11:29 UTC by LeeRim

## Description
> Event CRUD api 수정

## Chages
- event 수정 api response pk반환에서 void 반환하게 수정
    - UpdateEventRes 파일 삭제
- 이벤트 생성, 수정 request에 validation 적용
- 이벤트 조회 response 반환 항목 추가
    - 평점, 좋아요 유무, 좋아요 수, 북마크 여부, 리뷰 목록 추가

## ETC

2023-05-18 11:44 UTC, busymidnight requested changes

2023-05-18 11:44 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/dto/CreateEventReq.java
>  	private List<Long> categoryIds;
이벤트 생성시 카테고리, 이미지도 notnull이어야 할 것 같습니다!

2023-05-18 19:12 UTC, busymidnight requested changes

2023-05-18 19:12 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/dto/UpdateEventReq.java
>  	private List<Long> categoryIds;
여기도 카테고리, 이미지도 notnull이어야 할 것 같습니다!

2023-05-19 02:53 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/CreateEventReq.java
>  	private List<Long> categoryIds;
이벤트 이미지 1장 이상 필수인가요??

2023-05-19 05:27 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/dto/CreateEventReq.java
>  	private List<Long> categoryIds;
네네 이벤트 등록할때 이미지는 필수여야할거같아용
목록에서도 이미지가 보여야해서요!

2023-05-19 06:39 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/dto/CreateEventReq.java
>  	private List<Long> categoryIds;
네 알겠습니다

2023-05-19 06:54 UTC, busymidnight approved these changes

2023-05-19 06:55 UTC, merged