Feat: #351 - 북마크가 속한 폴더 변경 기능 구현
duck-map-project/duck-map-be pull request #352
Opened 2023-06-25 18:14 UTC by busymidnight

## Description

> 북마크가 속한 폴더 변경 기능 구현

## Changes

- BookmarkService
  - updateBookmark() 구현
- BookmarkController
  - updateBookmark() 구현
- BookmarkServiceTest
  - updateBookmark() 테스트 구현 
## ETC

2023-06-26 04:45 UTC, LeeRim requested changes
저 지금 봤는데 북마크 삭제 로직에서 id는 eventId입니다 수정하셔야 할거 같아요
헷갈리니까 controller에서 PathVariable에서 eventId라고 명시하는건 어떨까요?

2023-06-26 04:45 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/service/BookmarkService.java
> +			.findByIdWithLikeAndBookmark(eventId, member.getId())
이 메서드보다 eventId, memberId로 bookmark 조회하는 메서드를 구현해서 사용하는게 나을거 같아요

2023-06-26 04:45 UTC, LeeRim commented on src/test/java/com/teamddd/duckmap/service/BookmarkServiceTest.java
> +	EventLikeService likeService;
사용되지 않는거 같은데 추가하신 이유가 있나용?

2023-06-26 07:08 UTC, busymidnight commented on src/test/java/com/teamddd/duckmap/service/BookmarkServiceTest.java
> +	EventLikeService likeService;
> 사용되지 않는거 같은데 추가하신 이유가 있나용?

안 쓰는데 깜빡하고 안 지웠네요 😅

2023-06-26 07:55 UTC, busymidnight commented
> 저 지금 봤는데 북마크 삭제 로직에서 id는 eventId입니다 수정하셔야 할거 같아요
> 헷갈리니까 controller에서 PathVariable에서 eventId라고 명시하는건 어떨까요?

수정 완료 했습니닷

2023-06-26 08:25 UTC, LeeRim requested changes

2023-06-26 08:25 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/controller/BookmarkController.java
> +	public void deleteBookmark(@PathVariable Long eventId) {
이거 기능 돼요..?

2023-06-26 08:25 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/service/BookmarkService.java
> +			.orElseThrow(NonExistentEventException::new);
1. bookmarkRepository에서 findById면 bookmark Id로 조회하는게 맞는거 같아요. 메서드명이 어색해요
2. bookmark를 조회하는게 목적인데 event를 조회하는 상황이 주객전도 된거 같아요. Bookmark를 조회할 때 event를 join하는게 맞는거 같아요

2023-06-26 08:25 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +		return memberId != null ? eventBookmark.member.id.eq(memberId) : eventBookmark.member.id.isNull();
member id가 null이면 true인건가요..?

2023-06-26 08:35 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +		return memberId != null ? eventBookmark.member.id.eq(memberId) : eventBookmark.member.id.isNull();
> member id가 null이면 true인건가요..?

아니요..? null이 아닐때 true를 반환합니다

2023-06-26 08:41 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +		return memberId != null ? eventBookmark.member.id.eq(memberId) : eventBookmark.member.id.isNull();
> > member id가 null이면 true인건가요..?
> 
> 아니요..? null이 아닐때 true를 반환합니다
eventBookmark.member.id.isNull() 무슨? 코드인지 궁금합니다

2023-06-26 08:47 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +		return memberId != null ? eventBookmark.member.id.eq(memberId) : eventBookmark.member.id.isNull();
> > member id가 null이면 true인건가요..?
> 
> 아니요..? null이 아닐때 true를 반환합니다 eventBookmark.member.id.isNull() 무슨? 코드인지 궁금합니다

기존 코드에서는 null일때(false) eventBookmark.member.id도 null인지 확인하고자 사용했으나 
위에 제안해주신 from절에 eventBookmark가 오도록 쿼리를 변경하기 때문에 해당 코드는 삭제될 예정입니다!

2023-06-26 09:04 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/service/BookmarkService.java
> +			.orElseThrow(NonExistentEventException::new);
@LeeRim 메서드명 및 쿼리 수정 했습니다

2023-06-26 09:25 UTC, LeeRim requested changes

2023-06-26 09:25 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +	public Optional<BookmarkEventDto> findByEventIdAndMemberIdWithEvent(Long eventId, Long memberId) {
스프링 데이터로 구현 가능할거 같아요
@EntityGraph(attributePaths = {"event"}) 
findByEventAndMember()

근데 이벤트 존재 여부가 목적이라 event 전체 컬럼 조회하는게 맞는지 생각이 필요할거 같아요

2023-06-26 09:25 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/service/BookmarkService.java
> +			.findByEventIdAndMemberIdWithEvent(eventId, loginMemberId)
이벤트 존재도 확인하기 위해 조회했으니까 exception 던지게 수정해주세요

2023-06-26 09:29 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +	public Optional<BookmarkEventDto> findByEventIdAndMemberIdWithEvent(Long eventId, Long memberId) {
> 스프링 데이터로 구현 가능할거 같아요 @entitygraph(attributePaths = {"event"}) findByEventAndMember()
> 
> 근데 이벤트 존재 여부가 목적이라 event 전체 컬럼 조회하는게 맞는지 생각이 필요할거 같아요

생각해보니 event의 전체 컬럼을 사용할 일이 없을 것 같아서요. 
북마크에 eventId만 추가로 반환하는 Dto를 새로 생성하는게 나을까요?

2023-06-26 10:00 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +	public Optional<BookmarkEventDto> findByEventIdAndMemberIdWithEvent(Long eventId, Long memberId) {
> > 스프링 데이터로 구현 가능할거 같아요 @entitygraph(attributePaths = {"event"}) findByEventAndMember()
> > 근데 이벤트 존재 여부가 목적이라 event 전체 컬럼 조회하는게 맞는지 생각이 필요할거 같아요
> 
> 생각해보니 event의 전체 컬럼을 사용할 일이 없을 것 같아서요. 북마크에 eventId만 추가로 반환하는 Dto를 새로 생성하는게 나을까요?

음 어렵네욥
그래도 되고 아니면
inner join으로 조회하여 event가 없는 경우 bookmark도 조회 안되고 단순하게 bookmark exception 만 던지는 방법도 있습니다

2023-06-27 04:15 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +	public Optional<BookmarkEventDto> findByEventIdAndMemberIdWithEvent(Long eventId, Long memberId) {
@LeeRim 스프링데이터 사용하여 수정했습니닷

2023-06-27 04:23 UTC, LeeRim requested changes
Bookmark 조회 시 EntityGraph로 Event도 조회하실거면 service에서 exception 던져주세요
그냥 Bookmark Exception만 던지실거면 EntityGraph 지워주세요

BookmarkRepository Test 작성부탁드립니다

2023-06-27 04:23 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryCustom.java
> +	Optional<BookmarkEventDto> findtByEventAndMember(Long eventId, Long memberId);
스프링 데이터로 적용하려면 BookmarkRepository에 선언하셔야 해요

2023-06-27 04:23 UTC, LeeRim commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryImpl.java
> +	public Optional<BookmarkEventDto> findtByEventAndMember(Long eventId, Long memberId) {
스프링 데이터로 적용하면 메서드 구현한거 지워주세요

2023-06-27 04:25 UTC, busymidnight commented on src/main/java/com/teamddd/duckmap/repository/BookmarkRepositoryCustom.java
> +	Optional<BookmarkEventDto> findtByEventAndMember(Long eventId, Long memberId);
> 스프링 데이터로 적용하려면 BookmarkRepository에 선언하셔야 해요

앗 그렇군요 감사합니다!!

2023-06-27 05:47 UTC, LeeRim approved these changes

2023-06-27 06:14 UTC, merged